[package]
name = "backend-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
rust-embed = { version = "8.2.0" }
tokio = { version = "1.36.0", features = ["full"] }
warp = "0.3.6"
warp-embed = "0.5.0"
