[package]
name = "diff-tool-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.1"
serde = { version = "1.0.196", features = ["serde_derive"] }
walkdir = "2.4.0"

[dev-dependencies]
insta = { version = "1.34.0", features = ["serde", "toml", "json"] }
